-- RaceDayDatabase - Complete creation and population script
-- Code generated by GrokAI (AI) - September 20226

-- Create the database
IF EXISTS (SELECT name FROM sys.databases WHERE name = N'RaceDayDatabase')
BEGIN
    ALTER DATABASE RaceDayDatabase SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE RaceDayDatabase;
END
GO

CREATE DATABASE RaceDayDatabase;
GO

USE RaceDayDatabase;
GO

-- 1. UserAccount (base user table)
CREATE TABLE UserAccount 
(
    UserId INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    EmailAddress VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,          
    ImageUrl VARCHAR(255) NULL,
    Role VARCHAR(30) NOT NULL            
);
GO

-- 2. Participant (1:1 with UserAccount)
CREATE TABLE Participant 
(
    UserId INT NOT NULL PRIMARY KEY,
    Gender VARCHAR(20) NOT NULL,
    Age INT NOT NULL CHECK (Age > 0 AND Age < 120),
    Role  NVARCHAR(30) NOT NULL,        
    CONSTRAINT FK_Participant_UserAccount FOREIGN KEY (UserId) REFERENCES UserAccount(UserId)
        ON DELETE CASCADE
);
GO


-- 3. Organiser (1:1 with UserAccount)
CREATE TABLE Organiser 
(
    UserId INT NOT NULL PRIMARY KEY,
    AccessLevel NVARCHAR(30) NOT NULL,          
    CONSTRAINT FK_Organiser_UserAccount FOREIGN KEY (UserId) REFERENCES UserAccount(UserId)
        ON DELETE CASCADE
);
GO

-- 4. Category
CREATE TABLE Category 
(
    CategoryId INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    Title NVARCHAR(100) NOT NULL,
    Description NVARCHAR(500)   NULL
);
GO


-- 5. Route
CREATE TABLE Route 
(
    RouteId INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    RouteName VARCHAR(100) NOT NULL,
    Location VARCHAR(150) NOT NULL,
    Distance DECIMAL(6,2) NOT NULL,
    ImageUrl VARCHAR(255) NULL
);
GO


-- 6. Event
CREATE TABLE Event 
(
    EventId INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    UserId INT NOT NULL,          
    CategoryId INT NOT NULL,
    RouteId INT NOT NULL,
    Title VARCHAR(150) NOT NULL,
    Description VARCHAR(1000) NULL,
    StartLocation VARCHAR(150) NOT NULL,
    EndLocation VARCHAR(150) NOT NULL,
    StartTime TIME NOT NULL,
    Distance DECIMAL(6,2) NOT NULL,          
    [Date] DATE NOT NULL,
    ImageUrl VARCHAR(255) NULL,
    CONSTRAINT FK_Event_Organiser FOREIGN KEY (UserId) REFERENCES Organiser(UserId),
    CONSTRAINT FK_Event_Category FOREIGN KEY (CategoryId) REFERENCES Category(CategoryId),
    CONSTRAINT FK_Event_Route FOREIGN KEY (RouteId) REFERENCES Route(RouteId)
);
GO


-- 7. Enrolment
CREATE TABLE Enrolment 
(
    EnrolmentId INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    EventId INT NOT NULL,
    UserId INT NOT NULL,          
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    CONSTRAINT FK_Enrolment_Event FOREIGN KEY (EventId) REFERENCES Event(EventId),
    CONSTRAINT FK_Enrolment_Participant FOREIGN KEY (UserId) REFERENCES Participant(UserId),
    CONSTRAINT UQ_Enrolment_Event_User UNIQUE (EventId, UserId)  -- one enrolment per user per event
);
GO


-- 8. Result (1:1 with Enrolment)
CREATE TABLE Result 
(
    ResultsId INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    EnrolmentId INT NOT NULL UNIQUE,  
    [Time] TIME NOT NULL,   
    CONSTRAINT FK_Result_Enrolment FOREIGN KEY (EnrolmentId) REFERENCES Enrolment(EnrolmentId)
        ON DELETE CASCADE
);
GO


-- POPULATE TABLES (at least 3 rows each)

INSERT INTO UserAccount (FirstName, LastName, EmailAddress, Password, ImageUrl, Role) VALUES
('Thabo',   'Mokoena',  'thabo.mokoena@email.com',  'hashed_pw_thabo123',   'https://example.com/images/thabo.jpg',   'Participant'),
('Lerato',  'Dlamini',  'lerato.dlamini@email.com', 'hashed_pw_lerato456',  'https://example.com/images/lerato.jpg',  'Participant'),
('Johan',   'van Wyk',  'johan.vanwyk@email.com',   'hashed_pw_johan789',   'https://example.com/images/johan.jpg',   'Participant'),
('Sipho',   'Nkosi',    'sipho.nkosi@email.com',    'hashed_pw_sipho321',   'https://example.com/images/sipho.jpg',   'Organiser'),
('Aisha',   'Patel',    'aisha.patel@email.com',    'hashed_pw_aisha654',   'https://example.com/images/aisha.jpg',   'Organiser'),
('Pieter',  'Botha',    'pieter.botha@email.com',   'hashed_pw_pieter987',  'https://example.com/images/pieter.jpg',  'Organiser');
GO

-- ----- Participant (first 3 users) -----
INSERT INTO Participant (UserId, Gender, Age, Role) VALUES
(1, 'Male',   28, 'Participant'),
(2, 'Female', 32, 'Participant'),
(3, 'Male',   45, 'Participant');
GO

-- ----- Organiser (last 3 users) -----
INSERT INTO Organiser (UserId, AccessLevel) VALUES
(4, 'Full'),
(5, 'Full'),
(6, 'Limited');
GO

-- ----- Category -----
INSERT INTO Category (Title, Description) VALUES
('Road Race','Standard road running events on public roads'),
('Trail Run','Off-road running through natural terrain'),
('Fun Run','Shorter, community-oriented non-competitive runs'),
('Ultra Marathon','Races longer than the standard marathon distance');
GO

-- ----- Route -----
INSERT INTO Route (RouteName, Location, Distance, ImageUrl) VALUES
('Table Mountain Loop','Cape Town, Western Cape',12.50, 'https://example.com/routes/tablemtn.jpg'),
('Soweto Heritage Trail','Johannesburg, Gauteng',21.10, 'https://example.com/routes/soweto.jpg'),
('Durban Beachfront','Durban, KwaZulu-Natal',10.00, 'https://example.com/routes/durban.jpg'),
('Garden Route Challenge','Knysna, Western Cape',42.20, 'https://example.com/routes/gardenroute.jpg');
GO

-- ----- Event -----
INSERT INTO Event (UserId, CategoryId, RouteId, Title, Description, StartLocation, EndLocation, StartTime, Distance, [Date], ImageUrl) VALUES
(4, 1, 1, 'Cape Town 12K Challenge', 
    'A scenic road race around the base of Table Mountain.',
    'V&A Waterfront', 'Company''s Garden', '07:00:00', 12.50, '2026-10-15', 'https://example.com/events/ct12k.jpg'),

(5, 2, 2, 'Soweto Trail Run 21K', 
    'Experience the history and energy of Soweto on this trail half-marathon.',
    'Vilakazi Street', 'Soccer City', '06:30:00', 21.10, '2026-11-08', 'https://example.com/events/soweto21k.jpg'),

(4, 3, 3, 'Durban Fun Run 10K', 
    'Family-friendly fun run along the Golden Mile.',
    'North Beach', 'uShaka Marine World', '08:00:00', 10.00, '2026-09-20', 'https://example.com/events/durban10k.jpg'),

(6, 4, 4, 'Garden Route Ultra', 
    'Challenging ultra-marathon through the beautiful Garden Route.',
    'Knysna Heads', 'Plettenberg Bay', '05:00:00', 50.00, '2027-03-12', 'https://example.com/events/gardenultra.jpg');
GO

-- ----- Enrolment -----
INSERT INTO Enrolment (EventId, UserId, CreatedAt) VALUES
(1, 1, '2026-08-01 14:22:00'),   
(1, 2, '2026-08-03 09:15:00'),  
(2, 1, '2026-08-10 16:40:00'),  
(2, 3, '2026-08-12 11:05:00'),   
(3, 2, '2026-07-25 08:30:00'),   
(3, 3, '2026-07-28 19:50:00'),   
(4, 1, '2026-09-01 10:00:00');
GO

-- ----- Result -----
INSERT INTO Result (EnrolmentId, [Time]) VALUES
(1, '00:52:18'),  
(2, '00:58:45'),  
(3, '01:45:30'),   
(4, '02:12:05'), 
(5, '00:49:22'),   
(6, '01:05:17'); 
GO


PRINT '=== Row counts ===';
SELECT 'UserAccount' AS TableName, COUNT(*) AS 'RowCount' FROM UserAccount
UNION ALL SELECT 'Participant', COUNT(*) FROM Participant
UNION ALL SELECT 'Organiser', COUNT(*) FROM Organiser
UNION ALL SELECT 'Category', COUNT(*) FROM Category
UNION ALL SELECT 'Route', COUNT(*) FROM Route
UNION ALL SELECT 'Event', COUNT(*) FROM Event
UNION ALL SELECT 'Enrolment', COUNT(*) FROM Enrolment
UNION ALL SELECT 'Result', COUNT(*) FROM Result;
GO

PRINT 'Script completed successfully.';
GO
